import { NextRequest, NextResponse } from 'next/server';
import { createLogger } from '@/lib/logger';
import { jwtUtilsServer } from '@/lib/jwt-utils-server';

const logger = createLogger('users.me');

export async function GET(request: NextRequest) {
  const startTime = Date.now();
  logger.requestStart(request.method, request.url);

  try {
    // 获取 Authorization 头
    const authHeader = request.headers.get('Authorization');
    if (!authHeader) {
      logger.warn('Missing Authorization header');
      return NextResponse.json(
        { error: 'Authorization header is required' },
        { status: 401 }
      );
    }

    // 提取 JWT token
    const token = authHeader.replace('Bearer ', '');

    try {
      // 验证 Frontend JWT (由前端private key生成)
      const decoded = jwtUtilsServer.verifyToken(token);

      logger.info(
        'Frontend JWT verified successfully (generated by frontend private key)',
        {
          userId: decoded.sub,
          tenantId: decoded.tenant_id,
          tenantName: decoded.tenant_name,
          tokenType: decoded.type,
          email: decoded.email,
          jwtSource: 'frontend-generated',
          keyUsed: 'frontend_jwt_private_key.pem',
        }
      );

      // 返回用户信息（从JWT中获取）
      const userInfo = {
        id: parseInt(decoded.sub),
        email: decoded.email,
        tenant_id: decoded.tenant_id,
        tenant_name: decoded.tenant_name,
        is_active: true, // 如果JWT有效，说明用户是活跃的
      };

      const duration = Date.now() - startTime;
      logger.requestComplete(request.method, request.url, 200, duration);

      return NextResponse.json(userInfo);
    } catch (jwtError) {
      logger.error('Frontend JWT verification failed', {
        error: String(jwtError),
      });
      return NextResponse.json(
        { error: 'Invalid or expired JWT token' },
        { status: 401 }
      );
    }
  } catch (error) {
    logger.error('User profile request error', {
      error: error instanceof Error ? error.message : 'Unknown error',
    });
    const duration = Date.now() - startTime;
    logger.requestError(
      request.method,
      request.url,
      error instanceof Error ? error : new Error('Unknown error'),
      duration
    );
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
