"""add_complete_tenant_auth_models

Revision ID: 49ebd303fd21
Revises: 1d071ed2a34e
Create Date: 2025-08-12 18:57:57.873853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "49ebd303fd21"
down_revision = "1d071ed2a34e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jwt_blacklist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("token_type", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_jwt_blacklist_expires_at"),
        "jwt_blacklist",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_jwt_blacklist_id"), "jwt_blacklist", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_jwt_blacklist_tenant_id"),
        "jwt_blacklist",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_jwt_blacklist_token_hash"),
        "jwt_blacklist",
        ["token_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_jwt_blacklist_user_id"),
        "jwt_blacklist",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "system_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key_id", sa.String(), nullable=False),
        sa.Column(
            "key_type",
            sa.Enum(
                "JWT_SIGNING",
                "API_SIGNING",
                "WEBHOOK_SIGNING",
                name="systemkeytype",
            ),
            nullable=False,
        ),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("private_key_encrypted", sa.Text(), nullable=False),
        sa.Column("key_type_algorithm", sa.String(), nullable=False),
        sa.Column("key_size", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rotation_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_key_id", sa.String(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_keys_id"), "system_keys", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_system_keys_key_id"), "system_keys", ["key_id"], unique=True
    )
    op.create_table(
        "tenants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tenants_id"), "tenants", ["id"], unique=False)
    op.create_index(op.f("ix_tenants_name"), "tenants", ["name"], unique=True)
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key_id", sa.String(), nullable=False),
        sa.Column("key_hash", sa.String(), nullable=False),
        sa.Column("secret_hash", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column(
            "key_type",
            sa.Enum(
                "FRONTEND_SERVER",
                "BUSINESS_PARTNER",
                "SYSTEM",
                name="apikeytype",
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("allowed_ips", sa.JSON(), nullable=True),
        sa.Column("rate_limit", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_keys_id"), "api_keys", ["id"], unique=False)
    op.create_index(
        op.f("ix_api_keys_key_id"), "api_keys", ["key_id"], unique=True
    )
    op.create_table(
        "external_systems",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column(
            "system_type",
            sa.Enum(
                "SHOPIFY",
                "PRINTIFY",
                "AMAZON",
                "YAHOO",
                "RAKUTEN",
                name="externalsystemtype",
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("base_url", sa.String(), nullable=True),
        sa.Column("webhook_url", sa.String(), nullable=True),
        sa.Column("credentials", sa.JSON(), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("sync_enabled", sa.Boolean(), nullable=True),
        sa.Column("webhook_enabled", sa.Boolean(), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_interval_minutes", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_external_systems_id"),
        "external_systems",
        ["id"],
        unique=False,
    )
    op.create_table(
        "user_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("key_id", sa.String(), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("key_type", sa.String(), nullable=False),
        sa.Column("key_size", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_keys_id"), "user_keys", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_keys_key_id"), "user_keys", ["key_id"], unique=True
    )
    op.create_table(
        "user_tenants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("OWNER", "ADMIN", "USER", "VIEWER", name="userrole"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_tenants_id"), "user_tenants", ["id"], unique=False
    )
    op.create_table(
        "api_key_access_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_key_id", sa.Integer(), nullable=False),
        sa.Column("endpoint", sa.String(), nullable=False),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("request_data", sa.JSON(), nullable=True),
        sa.Column("response_time", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["api_keys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_api_key_access_logs_id"),
        "api_key_access_logs",
        ["id"],
        unique=False,
    )
    op.create_table(
        "external_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_system_id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column(
            "data_type",
            sa.Enum(
                "PRODUCT",
                "ORDER",
                "INVENTORY",
                "CUSTOMER",
                "SHIPPING",
                "PAYMENT",
                "WEBHOOK",
                name="externaldatatype",
            ),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("external_reference", sa.String(), nullable=True),
        sa.Column("raw_data", sa.JSON(), nullable=False),
        sa.Column("processed_data", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_processed", sa.Boolean(), nullable=True),
        sa.Column("processing_status", sa.String(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_version", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["external_system_id"],
            ["external_systems.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_external_data_id"), "external_data", ["id"], unique=False
    )
    op.create_table(
        "suppliers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("supplier_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("supplier_type", sa.String(), nullable=False),
        sa.Column("business_name", sa.String(), nullable=True),
        sa.Column("contact_person", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("external_data", sa.JSON(), nullable=True),
        sa.Column("api_credentials", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("external_system_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["external_system_id"],
            ["external_systems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_suppliers_id"), "suppliers", ["id"], unique=False)
    op.create_index(
        op.f("ix_suppliers_supplier_id"),
        "suppliers",
        ["supplier_id"],
        unique=True,
    )
    op.add_column(
        "customers", sa.Column("customer_id", sa.String(), nullable=False)
    )
    op.add_column(
        "customers", sa.Column("customer_type", sa.String(), nullable=False)
    )
    op.add_column(
        "customers", sa.Column("external_data", sa.JSON(), nullable=True)
    )
    op.add_column(
        "customers",
        sa.Column("external_system_id", sa.Integer(), nullable=False),
    )
    op.drop_index("ix_customers_email", table_name="customers")
    op.create_index(
        op.f("ix_customers_customer_id"),
        "customers",
        ["customer_id"],
        unique=True,
    )
    op.drop_constraint(
        "customers_owner_id_fkey", "customers", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "customers", "external_systems", ["external_system_id"], ["id"]
    )
    op.drop_column("customers", "shopify_store_url")
    op.drop_column("customers", "shopify_access_token")
    op.drop_column("customers", "printify_api_token")
    op.drop_column("customers", "shopify_api_secret")
    op.drop_column("customers", "auto_fulfillment")
    op.drop_column("customers", "webhook_enabled")
    op.drop_column("customers", "printify_shop_id")
    op.drop_column("customers", "shopify_api_key")
    op.drop_column("customers", "owner_id")
    op.add_column(
        "orders", sa.Column("tenant_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "orders", sa.Column("external_system_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("external_order_id", sa.String(), nullable=True)
    )
    op.add_column(
        "orders",
        sa.Column("external_order_number", sa.String(), nullable=True),
    )
    op.add_column(
        "orders", sa.Column("external_order_name", sa.String(), nullable=True)
    )
    op.drop_index("ix_orders_shopify_order_id", table_name="orders")
    op.drop_constraint("orders_customer_id_fkey", "orders", type_="foreignkey")
    op.create_foreign_key(None, "orders", "tenants", ["tenant_id"], ["id"])
    op.create_foreign_key(
        None, "orders", "external_systems", ["external_system_id"], ["id"]
    )
    op.drop_column("orders", "shopify_order_name")
    op.drop_column("orders", "customer_id")
    op.drop_column("orders", "shopify_order_id")
    op.drop_column("orders", "printify_order_id")
    op.drop_column("orders", "shopify_order_number")
    op.add_column(
        "products", sa.Column("tenant_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "products",
        sa.Column("external_system_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "products",
        sa.Column("external_product_id", sa.String(), nullable=True),
    )
    op.add_column(
        "products", sa.Column("external_data", sa.JSON(), nullable=True)
    )
    op.drop_index("ix_products_printify_product_id", table_name="products")
    op.create_foreign_key(None, "products", "tenants", ["tenant_id"], ["id"])
    op.create_foreign_key(
        None, "products", "external_systems", ["external_system_id"], ["id"]
    )
    op.drop_column("products", "print_areas")
    op.drop_column("products", "printify_product_id")
    op.drop_column("products", "print_provider_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "print_provider_id",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "printify_product_id",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "print_areas",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_constraint(None, "products", type_="foreignkey")
    op.create_index(
        "ix_products_printify_product_id",
        "products",
        ["printify_product_id"],
        unique=False,
    )
    op.drop_column("products", "external_data")
    op.drop_column("products", "external_product_id")
    op.drop_column("products", "external_system_id")
    op.drop_column("products", "tenant_id")
    op.add_column(
        "orders",
        sa.Column(
            "shopify_order_number",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "orders",
        sa.Column(
            "printify_order_id",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "orders",
        sa.Column(
            "shopify_order_id",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "orders",
        sa.Column(
            "customer_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "orders",
        sa.Column(
            "shopify_order_name",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.create_foreign_key(
        "orders_customer_id_fkey",
        "orders",
        "customers",
        ["customer_id"],
        ["id"],
    )
    op.create_index(
        "ix_orders_shopify_order_id",
        "orders",
        ["shopify_order_id"],
        unique=False,
    )
    op.drop_column("orders", "external_order_name")
    op.drop_column("orders", "external_order_number")
    op.drop_column("orders", "external_order_id")
    op.drop_column("orders", "external_system_id")
    op.drop_column("orders", "tenant_id")
    op.add_column(
        "customers",
        sa.Column(
            "owner_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "customers",
        sa.Column(
            "shopify_api_key", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "customers",
        sa.Column(
            "printify_shop_id",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "customers",
        sa.Column(
            "webhook_enabled", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "customers",
        sa.Column(
            "auto_fulfillment",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "customers",
        sa.Column(
            "shopify_api_secret",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "customers",
        sa.Column(
            "printify_api_token",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "customers",
        sa.Column(
            "shopify_access_token",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "customers",
        sa.Column(
            "shopify_store_url",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "customers", type_="foreignkey")
    op.create_foreign_key(
        "customers_owner_id_fkey", "customers", "users", ["owner_id"], ["id"]
    )
    op.drop_index(op.f("ix_customers_customer_id"), table_name="customers")
    op.create_index("ix_customers_email", "customers", ["email"], unique=False)
    op.drop_column("customers", "external_system_id")
    op.drop_column("customers", "external_data")
    op.drop_column("customers", "customer_type")
    op.drop_column("customers", "customer_id")
    op.drop_index(op.f("ix_suppliers_supplier_id"), table_name="suppliers")
    op.drop_index(op.f("ix_suppliers_id"), table_name="suppliers")
    op.drop_table("suppliers")
    op.drop_index(op.f("ix_external_data_id"), table_name="external_data")
    op.drop_table("external_data")
    op.drop_index(
        op.f("ix_api_key_access_logs_id"), table_name="api_key_access_logs"
    )
    op.drop_table("api_key_access_logs")
    op.drop_index(op.f("ix_user_tenants_id"), table_name="user_tenants")
    op.drop_table("user_tenants")
    op.drop_index(op.f("ix_user_keys_key_id"), table_name="user_keys")
    op.drop_index(op.f("ix_user_keys_id"), table_name="user_keys")
    op.drop_table("user_keys")
    op.drop_index(
        op.f("ix_external_systems_id"), table_name="external_systems"
    )
    op.drop_table("external_systems")
    op.drop_index(op.f("ix_api_keys_key_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_id"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_tenants_name"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_id"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_index(op.f("ix_system_keys_key_id"), table_name="system_keys")
    op.drop_index(op.f("ix_system_keys_id"), table_name="system_keys")
    op.drop_table("system_keys")
    op.drop_index(op.f("ix_jwt_blacklist_user_id"), table_name="jwt_blacklist")
    op.drop_index(
        op.f("ix_jwt_blacklist_token_hash"), table_name="jwt_blacklist"
    )
    op.drop_index(
        op.f("ix_jwt_blacklist_tenant_id"), table_name="jwt_blacklist"
    )
    op.drop_index(op.f("ix_jwt_blacklist_id"), table_name="jwt_blacklist")
    op.drop_index(
        op.f("ix_jwt_blacklist_expires_at"), table_name="jwt_blacklist"
    )
    op.drop_table("jwt_blacklist")
    # ### end Alembic commands ###
