"""fix_printify_orders_total_price_type

Revision ID: d259bc6512c5
Revises: 0b1200369700
Create Date: 2025-10-18 20:06:01.118097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd259bc6512c5'
down_revision = '0b1200369700'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('printify_orders', 'total_price',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True,
                postgresql_using="total_price::numeric(10,2)")
    op.drop_constraint(op.f('uq_product_mappings_tenant_core_variant_external'), 'product_mappings', type_='unique')
    op.create_unique_constraint('uq_product_mappings_tenant_core_external', 'product_mappings', ['tenant_id', 'core_product_id', 'external_system_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_mappings_tenant_core_external', 'product_mappings', type_='unique')
    op.create_unique_constraint(op.f('uq_product_mappings_tenant_core_variant_external'), 'product_mappings', ['tenant_id', 'core_product_id', 'core_variant_id', 'external_system_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('printify_orders', 'total_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
