"""Add SCM order routing tables

Revision ID: 639859f1099e
Revises: 96172cd884f4
Create Date: 2025-09-08 23:06:56.045107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "639859f1099e"
down_revision = "96172cd884f4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "routing_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("conditions", sa.JSON(), nullable=False),
        sa.Column("target_system_type", sa.String(), nullable=False),
        sa.Column("target_system_id", sa.String(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_routing_rules_id"), "routing_rules", ["id"], unique=False
    )
    op.create_table(
        "scm_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("source_order_id", sa.Integer(), nullable=False),
        sa.Column("target_system_type", sa.String(), nullable=False),
        sa.Column("target_system_id", sa.String(), nullable=True),
        sa.Column("scm_order_number", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("fulfillment_status", sa.String(), nullable=True),
        sa.Column("routing_metadata", sa.JSON(), nullable=True),
        sa.Column("routing_strategy", sa.String(), nullable=True),
        sa.Column("line_items", sa.JSON(), nullable=False),
        sa.Column(
            "total_amount", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("customer_email", sa.String(), nullable=False),
        sa.Column("customer_name", sa.String(), nullable=True),
        sa.Column("customer_phone", sa.String(), nullable=True),
        sa.Column("shipping_address", sa.JSON(), nullable=False),
        sa.Column("billing_address", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("last_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tracking_number", sa.String(), nullable=True),
        sa.Column("tracking_url", sa.String(), nullable=True),
        sa.Column("shopify_fulfillment_order_id", sa.String(), nullable=True),
        sa.Column("shopify_fulfillment_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fulfilled_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scm_order_number"),
    )
    op.create_index(
        op.f("ix_scm_orders_id"), "scm_orders", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_scm_orders_status"), "scm_orders", ["status"], unique=False
    )
    op.create_table(
        "routing_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("scm_order_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("routing_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scm_order_id"],
            ["scm_orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_routing_status_id"), "routing_status", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_routing_status_id"), table_name="routing_status")
    op.drop_table("routing_status")
    op.drop_index(op.f("ix_scm_orders_status"), table_name="scm_orders")
    op.drop_index(op.f("ix_scm_orders_id"), table_name="scm_orders")
    op.drop_table("scm_orders")
    op.drop_index(op.f("ix_routing_rules_id"), table_name="routing_rules")
    op.drop_table("routing_rules")
    # ### end Alembic commands ###
