"""Add Printify product models

Revision ID: c2fa9f2690ef
Revises: 2e9bd7c4a6f1
Create Date: 2025-10-12 11:41:26.481887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2fa9f2690ef'
down_revision = '2e9bd7c4a6f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printify_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('external_system_id', sa.Integer(), nullable=False),
    sa.Column('printify_product_id', sa.String(length=100), nullable=False),
    sa.Column('printify_shop_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('external', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('print_provider_id', sa.Integer(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('variants', sa.JSON(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('print_areas', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['external_system_id'], ['external_systems.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_system_id', 'printify_product_id', name='uq_printify_products_tenant_system_product')
    )
    op.create_index('idx_printify_products_created_at', 'printify_products', ['created_at'], unique=False)
    op.create_index('idx_printify_products_external_system_id', 'printify_products', ['external_system_id'], unique=False)
    op.create_index('idx_printify_products_printify_product_id', 'printify_products', ['printify_product_id'], unique=False)
    op.create_index('idx_printify_products_printify_shop_id', 'printify_products', ['printify_shop_id'], unique=False)
    op.create_index('idx_printify_products_sync_status', 'printify_products', ['sync_status'], unique=False)
    op.create_index('idx_printify_products_tenant_id', 'printify_products', ['tenant_id'], unique=False)
    op.create_index('idx_printify_products_tenant_system_product', 'printify_products', ['tenant_id', 'external_system_id', 'printify_product_id'], unique=False)
    op.create_index('idx_printify_products_visible', 'printify_products', ['visible'], unique=False)
    op.create_index(op.f('ix_printify_products_external_system_id'), 'printify_products', ['external_system_id'], unique=False)
    op.create_index(op.f('ix_printify_products_id'), 'printify_products', ['id'], unique=False)
    op.create_index(op.f('ix_printify_products_printify_product_id'), 'printify_products', ['printify_product_id'], unique=False)
    op.create_index(op.f('ix_printify_products_printify_shop_id'), 'printify_products', ['printify_shop_id'], unique=False)
    op.create_index(op.f('ix_printify_products_tenant_id'), 'printify_products', ['tenant_id'], unique=False)
    op.create_table('printify_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('printify_product_id', sa.Integer(), nullable=False),
    sa.Column('printify_variant_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('grams', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['printify_product_id'], ['printify_products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'printify_product_id', 'printify_variant_id', name='uq_printify_variants_tenant_product_variant')
    )
    op.create_index('idx_printify_variants_is_default', 'printify_variants', ['is_default'], unique=False)
    op.create_index('idx_printify_variants_is_enabled', 'printify_variants', ['is_enabled'], unique=False)
    op.create_index('idx_printify_variants_printify_product_id', 'printify_variants', ['printify_product_id'], unique=False)
    op.create_index('idx_printify_variants_printify_variant_id', 'printify_variants', ['printify_variant_id'], unique=False)
    op.create_index('idx_printify_variants_sku', 'printify_variants', ['sku'], unique=False)
    op.create_index('idx_printify_variants_tenant_id', 'printify_variants', ['tenant_id'], unique=False)
    op.create_index('idx_printify_variants_tenant_product_variant', 'printify_variants', ['tenant_id', 'printify_product_id', 'printify_variant_id'], unique=False)
    op.create_index(op.f('ix_printify_variants_id'), 'printify_variants', ['id'], unique=False)
    op.create_index(op.f('ix_printify_variants_printify_product_id'), 'printify_variants', ['printify_product_id'], unique=False)
    op.create_index(op.f('ix_printify_variants_printify_variant_id'), 'printify_variants', ['printify_variant_id'], unique=False)
    op.create_index(op.f('ix_printify_variants_sku'), 'printify_variants', ['sku'], unique=False)
    op.create_index(op.f('ix_printify_variants_tenant_id'), 'printify_variants', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_printify_variants_tenant_id'), table_name='printify_variants')
    op.drop_index(op.f('ix_printify_variants_sku'), table_name='printify_variants')
    op.drop_index(op.f('ix_printify_variants_printify_variant_id'), table_name='printify_variants')
    op.drop_index(op.f('ix_printify_variants_printify_product_id'), table_name='printify_variants')
    op.drop_index(op.f('ix_printify_variants_id'), table_name='printify_variants')
    op.drop_index('idx_printify_variants_tenant_product_variant', table_name='printify_variants')
    op.drop_index('idx_printify_variants_tenant_id', table_name='printify_variants')
    op.drop_index('idx_printify_variants_sku', table_name='printify_variants')
    op.drop_index('idx_printify_variants_printify_variant_id', table_name='printify_variants')
    op.drop_index('idx_printify_variants_printify_product_id', table_name='printify_variants')
    op.drop_index('idx_printify_variants_is_enabled', table_name='printify_variants')
    op.drop_index('idx_printify_variants_is_default', table_name='printify_variants')
    op.drop_table('printify_variants')
    op.drop_index(op.f('ix_printify_products_tenant_id'), table_name='printify_products')
    op.drop_index(op.f('ix_printify_products_printify_shop_id'), table_name='printify_products')
    op.drop_index(op.f('ix_printify_products_printify_product_id'), table_name='printify_products')
    op.drop_index(op.f('ix_printify_products_id'), table_name='printify_products')
    op.drop_index(op.f('ix_printify_products_external_system_id'), table_name='printify_products')
    op.drop_index('idx_printify_products_visible', table_name='printify_products')
    op.drop_index('idx_printify_products_tenant_system_product', table_name='printify_products')
    op.drop_index('idx_printify_products_tenant_id', table_name='printify_products')
    op.drop_index('idx_printify_products_sync_status', table_name='printify_products')
    op.drop_index('idx_printify_products_printify_shop_id', table_name='printify_products')
    op.drop_index('idx_printify_products_printify_product_id', table_name='printify_products')
    op.drop_index('idx_printify_products_external_system_id', table_name='printify_products')
    op.drop_index('idx_printify_products_created_at', table_name='printify_products')
    op.drop_table('printify_products')
    # ### end Alembic commands ###
