"""remove_system_keys_table

Revision ID: 023516327be5
Revises: 37b86ad0d4c1
Create Date: 2025-08-24 22:01:05.821303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "023516327be5"
down_revision = "37b86ad0d4c1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop system_keys table as it's not being used
    # All system keys are managed through environment variables
    op.drop_table("system_keys")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate system_keys table
    op.create_table(
        "system_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key_id", sa.String(), nullable=False),
        sa.Column(
            "key_type",
            sa.Enum(
                "JWT_SIGNING",
                "API_SIGNING", 
                "WEBHOOK_SIGNING",
                "FRONTEND_JWT_VERIFICATION",
                "THIRD_PARTY_JWT_VERIFICATION",
                name="systemkeytype",
            ),
            nullable=False,
        ),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("private_key_encrypted", sa.Text(), nullable=True),
        sa.Column("key_type_algorithm", sa.String(), nullable=False),
        sa.Column("key_size", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("system_identifier", sa.String(), nullable=True),
        sa.Column("system_name", sa.String(), nullable=True),
        sa.Column("system_version", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rotation_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_key_id", sa.String(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_keys_id"), "system_keys", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_system_keys_key_id"), "system_keys", ["key_id"], unique=True
    )
    # ### end Alembic commands ###
