"""add_verification_key_fields_to_system_keys

Revision ID: 37b86ad0d4c1
Revises: 9ff09b52ec69
Create Date: 2025-08-24 16:48:58.867080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "37b86ad0d4c1"
down_revision = "9ff09b52ec69"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "system_keys",
        sa.Column("system_identifier", sa.String(), nullable=True),
    )
    op.add_column(
        "system_keys", sa.Column("system_name", sa.String(), nullable=True)
    )
    op.add_column(
        "system_keys", sa.Column("system_version", sa.String(), nullable=True)
    )
    op.alter_column(
        "system_keys",
        "private_key_encrypted",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "system_keys",
        "private_key_encrypted",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.drop_column("system_keys", "system_version")
    op.drop_column("system_keys", "system_name")
    op.drop_column("system_keys", "system_identifier")
    # ### end Alembic commands ###
