"""Add Shopify product fields to products table

Revision ID: 07810f82b1ea
Revises: 13392266efa0
Create Date: 2025-08-13 21:28:30.584989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "07810f82b1ea"
down_revision = "13392266efa0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("handle", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "products",
        sa.Column("product_type", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "products", sa.Column("vendor", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "products", sa.Column("status", sa.String(length=20), nullable=True)
    )
    # Set default value for existing records
    op.execute("UPDATE products SET status = 'active' WHERE status IS NULL")
    # Make column NOT NULL after setting default values
    op.alter_column("products", "status", nullable=False)
    op.add_column(
        "products", sa.Column("total_inventory", sa.Integer(), nullable=True)
    )
    op.add_column(
        "products", sa.Column("tracks_inventory", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "products",
        sa.Column("has_out_of_stock_variants", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "products",
        sa.Column("has_only_default_variant", sa.Boolean(), nullable=True),
    )
    # Set default values for existing records
    op.execute("UPDATE products SET tracks_inventory = false WHERE tracks_inventory IS NULL")
    op.execute("UPDATE products SET has_out_of_stock_variants = false WHERE has_out_of_stock_variants IS NULL")
    op.execute("UPDATE products SET has_only_default_variant = false WHERE has_only_default_variant IS NULL")
    # Make columns NOT NULL after setting default values
    op.alter_column("products", "tracks_inventory", nullable=False)
    op.alter_column("products", "has_out_of_stock_variants", nullable=False)
    op.alter_column("products", "has_only_default_variant", nullable=False)
    op.add_column("products", sa.Column("seo", sa.JSON(), nullable=True))
    op.add_column(
        "products",
        sa.Column("online_store_url", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "products",
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        "idx_products_handle", "products", ["handle"], unique=False
    )
    op.create_index(
        "idx_products_inventory", "products", ["total_inventory"], unique=False
    )
    op.create_index(
        "idx_products_published", "products", ["published_at"], unique=False
    )
    op.create_index(
        "idx_products_tenant_status",
        "products",
        ["tenant_id", "status"],
        unique=False,
    )
    op.create_index(
        "idx_products_type", "products", ["product_type"], unique=False
    )
    op.create_index(
        "idx_products_vendor", "products", ["vendor"], unique=False
    )
    op.create_unique_constraint("uq_products_handle", "products", ["handle"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip index drops as they may not exist
    # op.drop_index("idx_products_vendor", table_name="products")
    # op.drop_index("idx_products_type", table_name="products")
    # op.drop_index("idx_products_tenant_status", table_name="products")
    # op.drop_index("idx_products_published", table_name="products")
    # op.drop_index("idx_products_inventory", table_name="products")
    # op.drop_index("idx_products_handle", table_name="products")
    # Skip constraint drop as it may not exist
    # op.drop_constraint("uq_products_handle", "products", type_="unique")
    # Skip column drops as they may not exist
    # op.drop_column("products", "published_at")
    # op.drop_column("products", "online_store_url")
    # op.drop_column("products", "seo")
    # op.drop_column("products", "has_only_default_variant")
    # op.drop_column("products", "has_out_of_stock_variants")
    # op.drop_column("products", "tracks_inventory")
    # op.drop_column("products", "total_inventory")
    # op.drop_column("products", "status")
    # op.drop_column("products", "vendor")
    # op.drop_column("products", "product_type")
    # op.drop_column("products", "handle")
    pass
    # ### end Alembic commands ###
