"""Add external_order_id and external_order_number to SCMOrder

Revision ID: 47a150b7658f
Revises: dd9935be82c8
Create Date: 2025-09-23 06:30:54.003521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "47a150b7658f"
down_revision = "dd9935be82c8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "status",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
    )
    op.alter_column(
        "products",
        "tracks_inventory",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.alter_column(
        "products",
        "has_out_of_stock_variants",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.alter_column(
        "products",
        "has_only_default_variant",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.drop_constraint("uq_products_handle", "products", type_="unique")
    op.add_column(
        "scm_orders",
        sa.Column("external_order_id", sa.String(), nullable=True),
    )
    op.add_column(
        "scm_orders",
        sa.Column("external_order_number", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scm_orders", "external_order_number")
    op.drop_column("scm_orders", "external_order_id")
    op.create_unique_constraint("uq_products_handle", "products", ["handle"])
    op.alter_column(
        "products",
        "has_only_default_variant",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "products",
        "has_out_of_stock_variants",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "products",
        "tracks_inventory",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "products",
        "status",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
    )
    # ### end Alembic commands ###
