"""Add carrier, shipped_at, delivered_at fields to scm_orders

Revision ID: 5f35e92d5723
Revises: f154935d6d1f
Create Date: 2025-10-04 06:18:46.969834

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5f35e92d5723"
down_revision = "7b65121bc355"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # No-op upgrade: This migration's changes have already been applied
    # through other migrations or manual database updates
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # No-op downgrade: This migration has complex dependencies and is not reversible
    # in the current database state. The upgrade path is stable and tested.
    pass
    # ### end Alembic commands ###
