"""add_shopify_json_fields_to_orders

Revision ID: 13392266efa0
Revises: 49ebd303fd21
Create Date: 2025-08-13 18:16:32.756787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "13392266efa0"
down_revision = "49ebd303fd21"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("order_number", sa.String(), nullable=True)
    )
    op.add_column(
        "orders",
        sa.Column(
            "subtotal_amount", sa.Numeric(precision=10, scale=2), nullable=True
        ),
    )
    op.add_column(
        "orders",
        sa.Column(
            "tax_amount", sa.Numeric(precision=10, scale=2), nullable=True
        ),
    )
    op.add_column(
        "orders", sa.Column("shopify_raw_data", sa.JSON(), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("shopify_processed", sa.JSON(), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("external_data", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip column drops as they may not exist
    # op.drop_column("orders", "external_data")
    # op.drop_column("orders", "shopify_processed")
    # op.drop_column("orders", "shopify_raw_data")
    # op.drop_column("orders", "tax_amount")
    # op.drop_column("orders", "subtotal_amount")
    # op.drop_column("orders", "order_number")
    pass
    # ### end Alembic commands ###
