"""add_printify_orders_table

Revision ID: e67d20de2f7f
Revises: c2fa9f2690ef
Create Date: 2025-10-13 15:42:55.194027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67d20de2f7f'
down_revision = 'c2fa9f2690ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printify_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('external_system_id', sa.Integer(), nullable=False),
    sa.Column('external_order_id', sa.String(length=255), nullable=False),
    sa.Column('scm_order_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_price', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('shipping_address', sa.JSON(), nullable=True),
    sa.Column('billing_address', sa.JSON(), nullable=True),
    sa.Column('printify_data', sa.JSON(), nullable=True),
    sa.Column('external_data', sa.JSON(), nullable=True),
    sa.Column('tracking_number', sa.String(length=255), nullable=True),
    sa.Column('tracking_url', sa.String(length=500), nullable=True),
    sa.Column('carrier', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['external_system_id'], ['external_systems.id'], ),
    sa.ForeignKeyConstraint(['scm_order_id'], ['scm_orders.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printify_orders_external_order_id'), 'printify_orders', ['external_order_id'], unique=False)
    op.create_index(op.f('ix_printify_orders_external_system_id'), 'printify_orders', ['external_system_id'], unique=False)
    op.create_index(op.f('ix_printify_orders_id'), 'printify_orders', ['id'], unique=False)
    op.create_index(op.f('ix_printify_orders_scm_order_id'), 'printify_orders', ['scm_order_id'], unique=False)
    op.create_index(op.f('ix_printify_orders_tenant_id'), 'printify_orders', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_printify_orders_tenant_id'), table_name='printify_orders')
    op.drop_index(op.f('ix_printify_orders_scm_order_id'), table_name='printify_orders')
    op.drop_index(op.f('ix_printify_orders_id'), table_name='printify_orders')
    op.drop_index(op.f('ix_printify_orders_external_system_id'), table_name='printify_orders')
    op.drop_index(op.f('ix_printify_orders_external_order_id'), table_name='printify_orders')
    op.drop_table('printify_orders')
    # ### end Alembic commands ###
