"""Add external_order_id and external_order_number to SCMOrder

Revision ID: 47a150b7658f
Revises: a0714620406e
Create Date: 2025-09-27 06:30:29.061169

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "47a150b7658f"
down_revision = "a0714620406e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # No-op upgrade: Changes have already been applied
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # No-op downgrade: Columns may not exist due to previous migrations
    pass
    # ### end Alembic commands ###
