"""Add external_system_id field and unique constraint

Revision ID: dd9935be82c8
Revises: 639859f1099e
Create Date: 2025-09-09 01:18:27.065446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dd9935be82c8"
down_revision = "639859f1099e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add the column as nullable first
    op.add_column(
        "external_systems",
        sa.Column("external_system_id", sa.String(length=100), nullable=True),
    )
    
    # Step 2: Update existing records with default values
    # Use external_id if available, otherwise use a generated value
    connection = op.get_bind()
    
    # Get all existing records
    result = connection.execute(
        sa.text("SELECT id, external_id, system_type, name FROM external_systems")
    )
    
    for row in result:
        external_system_id = row.external_id if row.external_id else f"{row.system_type}-{row.id}"
        
        connection.execute(
            sa.text(
                "UPDATE external_systems SET external_system_id = :external_system_id WHERE id = :id"
            ),
            {"external_system_id": external_system_id, "id": row.id}
        )
    
    # Step 3: Make the column NOT NULL
    op.alter_column(
        "external_systems",
        "external_system_id",
        nullable=False
    )
    
    # Step 4: Add unique constraint
    op.create_unique_constraint(
        "uq_tenant_system_external_id",
        "external_systems",
        ["tenant_id", "system_type", "external_system_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_tenant_system_external_id", "external_systems", type_="unique"
    )
    op.drop_column("external_systems", "external_system_id")
    # ### end Alembic commands ###