"""Add PIM core tables for dimensions, categories, and attributes

Revision ID: 6f98c9a0f611
Revises: e67d20de2f7f
Create Date: 2025-10-14 01:49:57.467506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6f98c9a0f611"
down_revision = "e67d20de2f7f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("category_code", sa.String(length=50), nullable=False),
        sa.Column("category_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_root", sa.Boolean(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "category_code", name="uq_category_tenant_code"
        ),
    )
    op.create_index(
        "ix_categories_tenant_active",
        "product_categories",
        ["tenant_id", "is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_categories_id"),
        "product_categories",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_categories_tenant_id"),
        "product_categories",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "product_dimension_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("dimension_code", sa.String(length=50), nullable=False),
        sa.Column("dimension_name", sa.String(length=200), nullable=False),
        sa.Column("dimension_type", sa.String(length=20), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "dimension_code",
            name="uq_dimension_template_tenant_code",
        ),
    )
    op.create_index(
        "ix_dimension_templates_tenant_active",
        "product_dimension_templates",
        ["tenant_id", "is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_dimension_templates_id"),
        "product_dimension_templates",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_dimension_templates_tenant_id"),
        "product_dimension_templates",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "product_category_dimensions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("dimension_template_id", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("source_category_id", sa.Integer(), nullable=True),
        sa.Column("is_required", sa.Boolean(), nullable=True),
        sa.Column("is_overridable", sa.Boolean(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["product_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dimension_template_id"],
            ["product_dimension_templates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_category_id"],
            ["product_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "category_id",
            "dimension_template_id",
            name="uq_category_dimension_category_template",
        ),
    )
    op.create_index(
        "ix_category_dimensions_category",
        "product_category_dimensions",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        "ix_category_dimensions_template",
        "product_category_dimensions",
        ["dimension_template_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_category_dimensions_category_id"),
        "product_category_dimensions",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_category_dimensions_dimension_template_id"),
        "product_category_dimensions",
        ["dimension_template_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_category_dimensions_id"),
        "product_category_dimensions",
        ["id"],
        unique=False,
    )
    op.create_table(
        "product_category_relations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_category_id", sa.Integer(), nullable=False),
        sa.Column("child_category_id", sa.Integer(), nullable=False),
        sa.Column("relation_type", sa.String(length=20), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.CheckConstraint(
            "parent_category_id != child_category_id",
            name="ck_category_relation_no_self",
        ),
        sa.ForeignKeyConstraint(
            ["child_category_id"],
            ["product_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_category_id"],
            ["product_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "parent_category_id",
            "child_category_id",
            name="uq_category_relation_parent_child",
        ),
    )
    op.create_index(
        "ix_category_relations_child",
        "product_category_relations",
        ["child_category_id"],
        unique=False,
    )
    op.create_index(
        "ix_category_relations_parent",
        "product_category_relations",
        ["parent_category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_category_relations_child_category_id"),
        "product_category_relations",
        ["child_category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_category_relations_id"),
        "product_category_relations",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_category_relations_parent_category_id"),
        "product_category_relations",
        ["parent_category_id"],
        unique=False,
    )
    op.create_table(
        "product_attributes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("attribute_key", sa.String(length=100), nullable=False),
        sa.Column("attribute_value", sa.Text(), nullable=True),
        sa.Column("attribute_type", sa.String(length=20), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "product_id",
            "attribute_key",
            name="uq_product_attribute_product_key",
        ),
    )
    op.create_index(
        op.f("ix_product_attributes_id"),
        "product_attributes",
        ["id"],
        unique=False,
    )
    op.create_index(
        "ix_product_attributes_key",
        "product_attributes",
        ["attribute_key"],
        unique=False,
    )
    op.create_index(
        "ix_product_attributes_product",
        "product_attributes",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_attributes_product_id"),
        "product_attributes",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "product_category_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["product_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "product_id",
            "category_id",
            name="uq_category_assignment_product_category",
        ),
    )
    op.create_index(
        "ix_category_assignments_category",
        "product_category_assignments",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        "ix_category_assignments_primary",
        "product_category_assignments",
        ["is_primary"],
        unique=False,
    )
    op.create_index(
        "ix_category_assignments_product",
        "product_category_assignments",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_category_assignments_category_id"),
        "product_category_assignments",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_category_assignments_id"),
        "product_category_assignments",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_category_assignments_product_id"),
        "product_category_assignments",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "product_dimension_values",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_dimension_id", sa.Integer(), nullable=False),
        sa.Column("value_code", sa.String(length=50), nullable=False),
        sa.Column("value_name", sa.String(length=200), nullable=False),
        sa.Column("value_type", sa.String(length=20), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("review_status", sa.String(length=20), nullable=True),
        sa.Column("merged_to_value_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("approved_by", sa.Integer(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_dimension_id"],
            ["product_category_dimensions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merged_to_value_id"],
            ["product_dimension_values.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "category_dimension_id",
            "value_code",
            name="uq_dimension_value_category_code",
        ),
    )
    op.create_index(
        "ix_dimension_values_category",
        "product_dimension_values",
        ["category_dimension_id"],
        unique=False,
    )
    op.create_index(
        "ix_dimension_values_status",
        "product_dimension_values",
        ["review_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_dimension_values_category_dimension_id"),
        "product_dimension_values",
        ["category_dimension_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_dimension_values_id"),
        "product_dimension_values",
        ["id"],
        unique=False,
    )
    op.create_table(
        "product_variant_attributes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("variant_id", sa.Integer(), nullable=False),
        sa.Column("attribute_key", sa.String(length=100), nullable=False),
        sa.Column("attribute_value", sa.Text(), nullable=True),
        sa.Column("attribute_type", sa.String(length=20), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("migrated_from_dimension", sa.Boolean(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "variant_id",
            "attribute_key",
            name="uq_variant_attribute_variant_key",
        ),
    )
    op.create_index(
        op.f("ix_product_variant_attributes_id"),
        "product_variant_attributes",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_variant_attributes_variant_id"),
        "product_variant_attributes",
        ["variant_id"],
        unique=False,
    )
    op.create_index(
        "ix_variant_attributes_key",
        "product_variant_attributes",
        ["attribute_key"],
        unique=False,
    )
    op.create_index(
        "ix_variant_attributes_migrated",
        "product_variant_attributes",
        ["migrated_from_dimension"],
        unique=False,
    )
    op.create_index(
        "ix_variant_attributes_variant",
        "product_variant_attributes",
        ["variant_id"],
        unique=False,
    )
    op.create_table(
        "product_variant_dimensions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("variant_id", sa.Integer(), nullable=False),
        sa.Column("dimension_template_id", sa.Integer(), nullable=False),
        sa.Column("dimension_value_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["dimension_template_id"],
            ["product_dimension_templates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dimension_value_id"],
            ["product_dimension_values.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "variant_id",
            "dimension_template_id",
            name="uq_variant_dimension_variant_template",
        ),
    )
    op.create_index(
        op.f("ix_product_variant_dimensions_dimension_template_id"),
        "product_variant_dimensions",
        ["dimension_template_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_variant_dimensions_dimension_value_id"),
        "product_variant_dimensions",
        ["dimension_value_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_variant_dimensions_id"),
        "product_variant_dimensions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_variant_dimensions_variant_id"),
        "product_variant_dimensions",
        ["variant_id"],
        unique=False,
    )
    op.create_index(
        "ix_variant_dimensions_template",
        "product_variant_dimensions",
        ["dimension_template_id"],
        unique=False,
    )
    op.create_index(
        "ix_variant_dimensions_value",
        "product_variant_dimensions",
        ["dimension_value_id"],
        unique=False,
    )
    op.create_index(
        "ix_variant_dimensions_variant",
        "product_variant_dimensions",
        ["variant_id"],
        unique=False,
    )
    op.alter_column(
        "order_items",
        "quantity",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "order_items",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # 安全地删除索引（如果存在的话）
    try:
        op.drop_index("ix_orders_shopify_order_id", table_name="orders")
    except Exception as e:
        # 索引不存在，记录日志但继续执行
        print(f"Index ix_orders_shopify_order_id does not exist, skipping: {e}")
        pass
    # 安全地删除索引（如果存在的话）
    connection = op.get_bind()
    result = connection.execute(sa.text("""
        SELECT indexname FROM pg_indexes 
        WHERE tablename = 'product_mappings' AND indexname = 'uq_pm_core_product'
    """))
    
    if result.fetchone():
        op.drop_index(
            "uq_pm_core_product",
            table_name="product_mappings",
            postgresql_where="(core_variant_id IS NULL)",
        )
        print("Index uq_pm_core_product dropped successfully")
    else:
        print("Index uq_pm_core_product does not exist, skipping")
    # 安全地删除索引（如果存在的话）
    result = connection.execute(sa.text("""
        SELECT indexname FROM pg_indexes 
        WHERE tablename = 'product_mappings' AND indexname = 'uq_pm_core_variant'
    """))
    
    if result.fetchone():
        op.drop_index(
            "uq_pm_core_variant",
            table_name="product_mappings",
            postgresql_where="(core_variant_id IS NOT NULL)",
        )
        print("Index uq_pm_core_variant dropped successfully")
    else:
        print("Index uq_pm_core_variant does not exist, skipping")
    # 安全地删除索引（如果存在的话）
    result = connection.execute(sa.text("""
        SELECT indexname FROM pg_indexes 
        WHERE tablename = 'product_mappings' AND indexname = 'uq_pm_ext_product'
    """))
    
    if result.fetchone():
        op.drop_index(
            "uq_pm_ext_product",
            table_name="product_mappings",
            postgresql_where="(external_variant_id IS NULL)",
        )
        print("Index uq_pm_ext_product dropped successfully")
    else:
        print("Index uq_pm_ext_product does not exist, skipping")
    # 安全地删除索引（如果存在的话）
    result = connection.execute(sa.text("""
        SELECT indexname FROM pg_indexes 
        WHERE tablename = 'product_mappings' AND indexname = 'uq_pm_ext_variant'
    """))
    
    if result.fetchone():
        op.drop_index(
            "uq_pm_ext_variant",
            table_name="product_mappings",
            postgresql_where="(external_variant_id IS NOT NULL)",
        )
        print("Index uq_pm_ext_variant dropped successfully")
    else:
        print("Index uq_pm_ext_variant does not exist, skipping")
    # Clean up duplicate data before creating unique constraint
    op.execute("""
        DELETE FROM product_mappings 
        WHERE id NOT IN (
            SELECT MIN(id) 
            FROM product_mappings 
            GROUP BY tenant_id, core_product_id, external_system_id
        )
    """)
    
    op.create_unique_constraint(
        "uq_product_mappings_tenant_core_external",
        "product_mappings",
        ["tenant_id", "core_product_id", "external_system_id"],
    )
    # 安全地删除约束（如果存在的话）
    result = connection.execute(sa.text("""
        SELECT constraint_name FROM information_schema.table_constraints 
        WHERE table_name = 'products' AND constraint_name = 'uq_products_handle'
    """))
    
    if result.fetchone():
        op.drop_constraint("uq_products_handle", "products", type_="unique")
        print("Constraint uq_products_handle dropped successfully")
    else:
        print("Constraint uq_products_handle does not exist, skipping")
    # 安全地删除索引（如果存在的话）
    result = connection.execute(sa.text("""
        SELECT indexname FROM pg_indexes 
        WHERE tablename = 'scm_orders' AND indexname = 'ix_scm_orders_printify_order_id'
    """))
    
    if result.fetchone():
        op.drop_index("ix_scm_orders_printify_order_id", table_name="scm_orders")
        print("Index ix_scm_orders_printify_order_id dropped successfully")
    else:
        print("Index ix_scm_orders_printify_order_id does not exist, skipping")
    
    result = connection.execute(sa.text("""
        SELECT indexname FROM pg_indexes 
        WHERE tablename = 'scm_orders' AND indexname = 'ix_scm_orders_shopify_order_id'
    """))
    
    if result.fetchone():
        op.drop_index("ix_scm_orders_shopify_order_id", table_name="scm_orders")
        print("Index ix_scm_orders_shopify_order_id dropped successfully")
    else:
        print("Index ix_scm_orders_shopify_order_id does not exist, skipping")
    # 安全地删除列（如果存在的话）
    columns_to_drop = ["total_amount", "target_system_type", "external_order_id", "external_order_number", "target_system_id"]
    
    for column_name in columns_to_drop:
        result = connection.execute(sa.text("""
            SELECT column_name FROM information_schema.columns 
            WHERE table_name = 'scm_orders' AND column_name = :column_name
        """), {"column_name": column_name})
        
        if result.fetchone():
            op.drop_column("scm_orders", column_name)
            print(f"Column {column_name} dropped successfully from scm_orders")
        else:
            print(f"Column {column_name} does not exist in scm_orders, skipping")
    op.create_index(
        op.f("ix_shopify_orders_id"), "shopify_orders", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_shopify_orders_shopify_order_id"),
        "shopify_orders",
        ["shopify_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_shopify_orders_tenant_id"),
        "shopify_orders",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_shopify_orders_tenant_id"), table_name="shopify_orders"
    )
    op.drop_index(
        op.f("ix_shopify_orders_shopify_order_id"), table_name="shopify_orders"
    )
    op.drop_index(op.f("ix_shopify_orders_id"), table_name="shopify_orders")
    op.add_column(
        "scm_orders",
        sa.Column(
            "target_system_id",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "scm_orders",
        sa.Column(
            "external_order_number",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "scm_orders",
        sa.Column(
            "external_order_id",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "scm_orders",
        sa.Column(
            "target_system_type",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "scm_orders",
        sa.Column(
            "total_amount", sa.NUMERIC(), autoincrement=False, nullable=True
        ),
    )
    op.create_index(
        "ix_scm_orders_shopify_order_id",
        "scm_orders",
        ["shopify_order_id"],
        unique=False,
    )
    op.create_index(
        "ix_scm_orders_printify_order_id",
        "scm_orders",
        ["printify_order_id"],
        unique=False,
    )
    op.create_unique_constraint("uq_products_handle", "products", ["handle"])
    op.drop_constraint(
        "uq_product_mappings_tenant_core_external",
        "product_mappings",
        type_="unique",
    )
    op.create_index(
        "uq_pm_ext_variant",
        "product_mappings",
        [
            "tenant_id",
            "external_system_id",
            "external_product_id",
            "external_variant_id",
        ],
        unique=False,
        postgresql_where="(external_variant_id IS NOT NULL)",
    )
    op.create_index(
        "uq_pm_ext_product",
        "product_mappings",
        ["tenant_id", "external_system_id", "external_product_id"],
        unique=False,
        postgresql_where="(external_variant_id IS NULL)",
    )
    op.create_index(
        "uq_pm_core_variant",
        "product_mappings",
        [
            "tenant_id",
            "external_system_id",
            "core_product_id",
            "core_variant_id",
        ],
        unique=False,
        postgresql_where="(core_variant_id IS NOT NULL)",
    )
    op.create_index(
        "uq_pm_core_product",
        "product_mappings",
        ["tenant_id", "external_system_id", "core_product_id"],
        unique=False,
        postgresql_where="(core_variant_id IS NULL)",
    )
    op.create_index(
        "ix_orders_shopify_order_id",
        "orders",
        ["shopify_order_id"],
        unique=False,
    )
    op.alter_column(
        "order_items",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "order_items",
        "quantity",
        existing_type=sa.INTEGER(),
        server_default=sa.text("1"),
        existing_nullable=False,
    )
    op.drop_index(
        "ix_variant_dimensions_variant",
        table_name="product_variant_dimensions",
    )
    op.drop_index(
        "ix_variant_dimensions_value", table_name="product_variant_dimensions"
    )
    op.drop_index(
        "ix_variant_dimensions_template",
        table_name="product_variant_dimensions",
    )
    op.drop_index(
        op.f("ix_product_variant_dimensions_variant_id"),
        table_name="product_variant_dimensions",
    )
    op.drop_index(
        op.f("ix_product_variant_dimensions_id"),
        table_name="product_variant_dimensions",
    )
    op.drop_index(
        op.f("ix_product_variant_dimensions_dimension_value_id"),
        table_name="product_variant_dimensions",
    )
    op.drop_index(
        op.f("ix_product_variant_dimensions_dimension_template_id"),
        table_name="product_variant_dimensions",
    )
    op.drop_table("product_variant_dimensions")
    op.drop_index(
        "ix_variant_attributes_variant",
        table_name="product_variant_attributes",
    )
    op.drop_index(
        "ix_variant_attributes_migrated",
        table_name="product_variant_attributes",
    )
    op.drop_index(
        "ix_variant_attributes_key", table_name="product_variant_attributes"
    )
    op.drop_index(
        op.f("ix_product_variant_attributes_variant_id"),
        table_name="product_variant_attributes",
    )
    op.drop_index(
        op.f("ix_product_variant_attributes_id"),
        table_name="product_variant_attributes",
    )
    op.drop_table("product_variant_attributes")
    op.drop_index(
        op.f("ix_product_dimension_values_id"),
        table_name="product_dimension_values",
    )
    op.drop_index(
        op.f("ix_product_dimension_values_category_dimension_id"),
        table_name="product_dimension_values",
    )
    op.drop_index(
        "ix_dimension_values_status", table_name="product_dimension_values"
    )
    op.drop_index(
        "ix_dimension_values_category", table_name="product_dimension_values"
    )
    op.drop_table("product_dimension_values")
    op.drop_index(
        op.f("ix_product_category_assignments_product_id"),
        table_name="product_category_assignments",
    )
    op.drop_index(
        op.f("ix_product_category_assignments_id"),
        table_name="product_category_assignments",
    )
    op.drop_index(
        op.f("ix_product_category_assignments_category_id"),
        table_name="product_category_assignments",
    )
    op.drop_index(
        "ix_category_assignments_product",
        table_name="product_category_assignments",
    )
    op.drop_index(
        "ix_category_assignments_primary",
        table_name="product_category_assignments",
    )
    op.drop_index(
        "ix_category_assignments_category",
        table_name="product_category_assignments",
    )
    op.drop_table("product_category_assignments")
    op.drop_index(
        op.f("ix_product_attributes_product_id"),
        table_name="product_attributes",
    )
    op.drop_index(
        "ix_product_attributes_product", table_name="product_attributes"
    )
    op.drop_index("ix_product_attributes_key", table_name="product_attributes")
    op.drop_index(
        op.f("ix_product_attributes_id"), table_name="product_attributes"
    )
    op.drop_table("product_attributes")
    op.drop_index(
        op.f("ix_product_category_relations_parent_category_id"),
        table_name="product_category_relations",
    )
    op.drop_index(
        op.f("ix_product_category_relations_id"),
        table_name="product_category_relations",
    )
    op.drop_index(
        op.f("ix_product_category_relations_child_category_id"),
        table_name="product_category_relations",
    )
    op.drop_index(
        "ix_category_relations_parent", table_name="product_category_relations"
    )
    op.drop_index(
        "ix_category_relations_child", table_name="product_category_relations"
    )
    op.drop_table("product_category_relations")
    op.drop_index(
        op.f("ix_product_category_dimensions_id"),
        table_name="product_category_dimensions",
    )
    op.drop_index(
        op.f("ix_product_category_dimensions_dimension_template_id"),
        table_name="product_category_dimensions",
    )
    op.drop_index(
        op.f("ix_product_category_dimensions_category_id"),
        table_name="product_category_dimensions",
    )
    op.drop_index(
        "ix_category_dimensions_template",
        table_name="product_category_dimensions",
    )
    op.drop_index(
        "ix_category_dimensions_category",
        table_name="product_category_dimensions",
    )
    op.drop_table("product_category_dimensions")
    op.drop_index(
        op.f("ix_product_dimension_templates_tenant_id"),
        table_name="product_dimension_templates",
    )
    op.drop_index(
        op.f("ix_product_dimension_templates_id"),
        table_name="product_dimension_templates",
    )
    op.drop_index(
        "ix_dimension_templates_tenant_active",
        table_name="product_dimension_templates",
    )
    op.drop_table("product_dimension_templates")
    op.drop_index(
        op.f("ix_product_categories_tenant_id"),
        table_name="product_categories",
    )
    op.drop_index(
        op.f("ix_product_categories_id"), table_name="product_categories"
    )
    op.drop_index(
        "ix_categories_tenant_active", table_name="product_categories"
    )
    op.drop_table("product_categories")
    # ### end Alembic commands ###
