"""Make source_order_id nullable in SCMOrder

Revision ID: 7beb7b99f65f
Revises: 47a150b7658f
Create Date: 2025-09-23 07:04:26.467085

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7beb7b99f65f"
down_revision = "47a150b7658f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scm_orders",
        "source_order_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scm_orders",
        "source_order_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
