"""Add carrier, shipped_at, delivered_at fields to scm_orders

Revision ID: 5f35e92d5723
Revises: f154935d6d1f
Create Date: 2025-10-04 06:18:46.969834

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5f35e92d5723"
down_revision = "7b65121bc355"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop index with error handling
    try:
        op.drop_index("ix_orders_shopify_order_id", table_name="orders")
    except Exception:
        pass  # Index doesn't exist, continue
    # Drop constraint with error handling
    try:
        op.drop_constraint(
            "uq_product_mappings_tenant_variant_external",
            "product_mappings",
            type_="unique",
        )
    except Exception:
        pass  # Constraint doesn't exist, continue
    op.create_unique_constraint(
        "uq_product_mappings_tenant_core_external",
        "product_mappings",
        ["tenant_id", "core_product_id", "external_system_id"],
    )
    op.add_column("scm_orders", sa.Column("carrier", sa.String(), nullable=True))
    op.add_column(
        "scm_orders",
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "scm_orders",
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
    )
    # Drop indexes with error handling
    try:
        op.drop_index("ix_scm_orders_printify_order_id", table_name="scm_orders")
    except Exception:
        pass  # Index doesn't exist, continue
    try:
        op.drop_index("ix_scm_orders_shopify_order_id", table_name="scm_orders")
    except Exception:
        pass  # Index doesn't exist, continue
    op.drop_column("scm_orders", "external_order_number")
    op.drop_column("scm_orders", "external_order_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scm_orders",
        sa.Column(
            "external_order_id",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "scm_orders",
        sa.Column(
            "external_order_number",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        "ix_scm_orders_shopify_order_id",
        "scm_orders",
        ["shopify_order_id"],
        unique=False,
    )
    op.create_index(
        "ix_scm_orders_printify_order_id",
        "scm_orders",
        ["printify_order_id"],
        unique=False,
    )
    op.drop_column("scm_orders", "delivered_at")
    op.drop_column("scm_orders", "shipped_at")
    op.drop_column("scm_orders", "carrier")
    op.drop_constraint(
        "uq_product_mappings_tenant_core_external",
        "product_mappings",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_product_mappings_tenant_variant_external",
        "product_mappings",
        ["tenant_id", "core_variant_id", "external_system_id"],
    )
    op.create_index(
        "ix_orders_shopify_order_id",
        "orders",
        ["shopify_order_id"],
        unique=False,
    )
    # ### end Alembic commands ###
