"""Add sync config and job models - retry

Revision ID: c9625bb15029
Revises: cbc267b6575b
Create Date: 2025-08-13 22:27:22.539287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c9625bb15029"
down_revision = "cbc267b6575b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("external_system_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "sync_type",
            sa.Enum(
                "PRODUCTS", "ORDERS", "CUSTOMERS", "INVENTORY", name="synctype"
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "frequency",
            sa.Enum(
                "MANUAL",
                "HOURLY",
                "DAILY",
                "WEEKLY",
                "CUSTOM",
                name="syncfrequency",
            ),
            nullable=False,
        ),
        sa.Column("custom_interval_minutes", sa.Integer(), nullable=True),
        sa.Column("sync_params", sa.JSON(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_runs", sa.Integer(), nullable=False),
        sa.Column("successful_runs", sa.Integer(), nullable=False),
        sa.Column("failed_runs", sa.Integer(), nullable=False),
        sa.Column("total_items_processed", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["external_system_id"],
            ["external_systems.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_sync_configs_active", "sync_configs", ["is_active"], unique=False
    )
    op.create_index(
        "idx_sync_configs_next_run",
        "sync_configs",
        ["next_run_at"],
        unique=False,
    )
    op.create_index(
        "idx_sync_configs_tenant_type",
        "sync_configs",
        ["tenant_id", "sync_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sync_configs_id"), "sync_configs", ["id"], unique=False
    )
    op.create_table(
        "sync_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sync_config_id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "SUCCESS",
                "FAILED",
                "CANCELLED",
                name="syncjobstatus",
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("items_processed", sa.Integer(), nullable=False),
        sa.Column("items_created", sa.Integer(), nullable=False),
        sa.Column("items_updated", sa.Integer(), nullable=False),
        sa.Column("items_failed", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_details", sa.JSON(), nullable=True),
        sa.Column("progress_percentage", sa.Integer(), nullable=False),
        sa.Column("progress_message", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["sync_config_id"],
            ["sync_configs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_sync_jobs_config_status",
        "sync_jobs",
        ["sync_config_id", "status"],
        unique=False,
    )
    op.create_index(
        "idx_sync_jobs_created", "sync_jobs", ["created_at"], unique=False
    )
    op.create_index(
        "idx_sync_jobs_tenant_status",
        "sync_jobs",
        ["tenant_id", "status"],
        unique=False,
    )
    op.create_index(op.f("ix_sync_jobs_id"), "sync_jobs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes safely
    op.execute("DROP INDEX IF EXISTS ix_sync_jobs_id")
    op.execute("DROP INDEX IF EXISTS idx_sync_jobs_tenant_status")
    op.execute("DROP INDEX IF EXISTS idx_sync_jobs_created")
    op.execute("DROP INDEX IF EXISTS idx_sync_jobs_config_status")
    op.execute("DROP TABLE IF EXISTS sync_jobs")
    op.execute("DROP INDEX IF EXISTS ix_sync_configs_id")
    op.execute("DROP INDEX IF EXISTS idx_sync_configs_tenant_type")
    op.execute("DROP INDEX IF EXISTS idx_sync_configs_next_run")
    op.execute("DROP INDEX IF EXISTS idx_sync_configs_active")
    op.execute("DROP TABLE IF EXISTS sync_configs")
    
    # Drop enum types
    op.execute("DROP TYPE IF EXISTS syncjobstatus")
    op.execute("DROP TYPE IF EXISTS syncfrequency")
    op.execute("DROP TYPE IF EXISTS synctype")
    # ### end Alembic commands ###
