"""Replace products table with new flexible product system

Revision ID: 61f7bbff7894
Revises: dd9935be82c8
Create Date: 2025-09-23 18:46:45.488073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "61f7bbff7894"
down_revision = "dd9935be82c8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_tags_tenant_name"),
    )
    op.create_index(
        "idx_tags_tenant_category",
        "tags",
        ["tenant_id", "category"],
        unique=False,
    )
    op.create_index(
        "idx_tags_tenant_name", "tags", ["tenant_id", "name"], unique=False
    )
    op.create_index(op.f("ix_tags_id"), "tags", ["id"], unique=False)
    op.create_index(
        op.f("ix_tags_tenant_id"), "tags", ["tenant_id"], unique=False
    )
    op.create_table(
        "barcode_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("format_pattern", sa.String(length=100), nullable=True),
        sa.Column("length_min", sa.Integer(), nullable=True),
        sa.Column("length_max", sa.Integer(), nullable=True),
        sa.Column("external_system_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["external_system_id"],
            ["external_systems.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "name", name="uq_barcode_types_tenant_name"
        ),
    )
    op.create_index(
        "idx_barcode_types_tenant_name",
        "barcode_types",
        ["tenant_id", "name"],
        unique=False,
    )
    op.create_index(
        "idx_barcode_types_tenant_system",
        "barcode_types",
        ["tenant_id", "external_system_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_barcode_types_id"), "barcode_types", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_barcode_types_tenant_id"),
        "barcode_types",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "external_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("external_system_id", sa.Integer(), nullable=False),
        sa.Column(
            "external_product_id", sa.String(length=100), nullable=False
        ),
        sa.Column("external_variant_id", sa.String(length=100), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("handle", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "compare_at_price",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
        ),
        sa.Column(
            "cost_price", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column("inventory_quantity", sa.Integer(), nullable=True),
        sa.Column("inventory_policy", sa.String(length=20), nullable=True),
        sa.Column("product_type", sa.String(length=100), nullable=True),
        sa.Column("vendor", sa.String(length=100), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("images", sa.JSON(), nullable=True),
        sa.Column("variants", sa.JSON(), nullable=True),
        sa.Column("external_data", sa.JSON(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_status", sa.String(length=20), nullable=False),
        sa.Column("sync_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["external_system_id"],
            ["external_systems.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "external_system_id",
            "external_product_id",
            "external_variant_id",
            name="uq_external_products_tenant_system_product_variant",
        ),
    )
    op.create_index(
        "idx_external_products_tenant_product",
        "external_products",
        ["tenant_id", "external_product_id"],
        unique=False,
    )
    op.create_index(
        "idx_external_products_tenant_status",
        "external_products",
        ["tenant_id", "status"],
        unique=False,
    )
    op.create_index(
        "idx_external_products_tenant_sync",
        "external_products",
        ["tenant_id", "sync_status"],
        unique=False,
    )
    op.create_index(
        "idx_external_products_tenant_system",
        "external_products",
        ["tenant_id", "external_system_id"],
        unique=False,
    )
    op.create_index(
        "idx_external_products_tenant_variant",
        "external_products",
        ["tenant_id", "external_variant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_products_external_product_id"),
        "external_products",
        ["external_product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_products_external_system_id"),
        "external_products",
        ["external_system_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_products_external_variant_id"),
        "external_products",
        ["external_variant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_products_id"),
        "external_products",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_products_tenant_id"),
        "external_products",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "product_combinations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("combination_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("combination_type", sa.String(length=50), nullable=False),
        sa.Column("price_strategy", sa.String(length=50), nullable=False),
        sa.Column(
            "combination_price",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
        ),
        sa.Column(
            "discount_percentage",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
        ),
        sa.Column("inventory_policy", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_product_combinations_tenant_product",
        "product_combinations",
        ["tenant_id", "product_id"],
        unique=False,
    )
    op.create_index(
        "idx_product_combinations_tenant_type",
        "product_combinations",
        ["tenant_id", "combination_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_combinations_id"),
        "product_combinations",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_combinations_product_id"),
        "product_combinations",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_combinations_tenant_id"),
        "product_combinations",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "product_dimensions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("dimension_name", sa.String(length=50), nullable=False),
        sa.Column("dimension_type", sa.String(length=20), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("validation_rules", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "product_id",
            "dimension_name",
            name="uq_product_dimensions_tenant_product_name",
        ),
    )
    op.create_index(
        "idx_product_dimensions_name",
        "product_dimensions",
        ["tenant_id", "dimension_name"],
        unique=False,
    )
    op.create_index(
        "idx_product_dimensions_tenant_product",
        "product_dimensions",
        ["tenant_id", "product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_dimensions_id"),
        "product_dimensions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_dimensions_product_id"),
        "product_dimensions",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_dimensions_tenant_id"),
        "product_dimensions",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "product_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "product_id",
            "tag_id",
            name="uq_product_tags_tenant_product_tag",
        ),
    )
    op.create_index(
        "idx_product_tags_primary",
        "product_tags",
        ["tenant_id", "is_primary"],
        unique=False,
    )
    op.create_index(
        "idx_product_tags_tenant_product",
        "product_tags",
        ["tenant_id", "product_id"],
        unique=False,
    )
    op.create_index(
        "idx_product_tags_tenant_tag",
        "product_tags",
        ["tenant_id", "tag_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_tags_id"), "product_tags", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_product_tags_product_id"),
        "product_tags",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_tags_tag_id"),
        "product_tags",
        ["tag_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_tags_tenant_id"),
        "product_tags",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "product_variants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=True),
        sa.Column("barcode", sa.String(length=50), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "compare_at_price",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
        ),
        sa.Column(
            "cost_price", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column("inventory_quantity", sa.Integer(), nullable=False),
        sa.Column("inventory_policy", sa.String(length=20), nullable=False),
        sa.Column("tracks_inventory", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("weight", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("dimensions", sa.JSON(), nullable=True),
        sa.Column("external_variant_id", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "sku", name="uq_product_variants_tenant_sku"
        ),
    )
    op.create_index(
        "idx_product_variants_inventory",
        "product_variants",
        ["tenant_id", "inventory_quantity"],
        unique=False,
    )
    op.create_index(
        "idx_product_variants_tenant_barcode",
        "product_variants",
        ["tenant_id", "barcode"],
        unique=False,
    )
    op.create_index(
        "idx_product_variants_tenant_product",
        "product_variants",
        ["tenant_id", "product_id"],
        unique=False,
    )
    op.create_index(
        "idx_product_variants_tenant_sku",
        "product_variants",
        ["tenant_id", "sku"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_variants_barcode"),
        "product_variants",
        ["barcode"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_variants_id"),
        "product_variants",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_variants_product_id"),
        "product_variants",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_variants_sku"),
        "product_variants",
        ["sku"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_variants_tenant_id"),
        "product_variants",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "product_combination_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("combination_id", sa.Integer(), nullable=False),
        sa.Column("item_product_id", sa.Integer(), nullable=False),
        sa.Column("item_variant_id", sa.Integer(), nullable=True),
        sa.Column("quantity_min", sa.Integer(), nullable=False),
        sa.Column("quantity_max", sa.Integer(), nullable=True),
        sa.Column("quantity_default", sa.Integer(), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["combination_id"],
            ["product_combinations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_variant_id"],
            ["product_variants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_product_combination_items_tenant_combination",
        "product_combination_items",
        ["tenant_id", "combination_id"],
        unique=False,
    )
    op.create_index(
        "idx_product_combination_items_tenant_product",
        "product_combination_items",
        ["tenant_id", "item_product_id"],
        unique=False,
    )
    op.create_index(
        "idx_product_combination_items_tenant_variant",
        "product_combination_items",
        ["tenant_id", "item_variant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_combination_items_combination_id"),
        "product_combination_items",
        ["combination_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_combination_items_id"),
        "product_combination_items",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_combination_items_item_product_id"),
        "product_combination_items",
        ["item_product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_combination_items_item_variant_id"),
        "product_combination_items",
        ["item_variant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_combination_items_tenant_id"),
        "product_combination_items",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "product_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("core_product_id", sa.Integer(), nullable=False),
        sa.Column("core_variant_id", sa.Integer(), nullable=True),
        sa.Column("external_system_id", sa.Integer(), nullable=False),
        sa.Column(
            "external_product_id", sa.String(length=100), nullable=False
        ),
        sa.Column("external_variant_id", sa.String(length=100), nullable=True),
        sa.Column("mapping_type", sa.String(length=50), nullable=False),
        sa.Column("sync_direction", sa.String(length=20), nullable=False),
        sa.Column("sync_status", sa.String(length=20), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_error", sa.Text(), nullable=True),
        sa.Column("sync_config", sa.JSON(), nullable=True),
        sa.Column("field_mappings", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["core_product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["core_variant_id"],
            ["product_variants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["external_system_id"],
            ["external_systems.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "core_product_id",
            "external_system_id",
            name="uq_product_mappings_tenant_core_external",
        ),
    )
    op.create_index(
        "idx_product_mappings_external_product",
        "product_mappings",
        ["tenant_id", "external_system_id", "external_product_id"],
        unique=False,
    )
    op.create_index(
        "idx_product_mappings_tenant_core",
        "product_mappings",
        ["tenant_id", "core_product_id"],
        unique=False,
    )
    op.create_index(
        "idx_product_mappings_tenant_external",
        "product_mappings",
        ["tenant_id", "external_system_id"],
        unique=False,
    )
    op.create_index(
        "idx_product_mappings_tenant_sync",
        "product_mappings",
        ["tenant_id", "sync_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_mappings_core_product_id"),
        "product_mappings",
        ["core_product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_mappings_core_variant_id"),
        "product_mappings",
        ["core_variant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_mappings_external_product_id"),
        "product_mappings",
        ["external_product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_mappings_external_system_id"),
        "product_mappings",
        ["external_system_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_mappings_external_variant_id"),
        "product_mappings",
        ["external_variant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_mappings_id"),
        "product_mappings",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_mappings_tenant_id"),
        "product_mappings",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "variant_attributes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("variant_id", sa.Integer(), nullable=False),
        sa.Column("dimension_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(length=200), nullable=False),
        sa.Column("display_value", sa.String(length=200), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["dimension_id"],
            ["product_dimensions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "variant_id",
            "dimension_id",
            name="uq_variant_attributes_tenant_variant_dimension",
        ),
    )
    op.create_index(
        "idx_variant_attributes_tenant_dimension",
        "variant_attributes",
        ["tenant_id", "dimension_id"],
        unique=False,
    )
    op.create_index(
        "idx_variant_attributes_tenant_variant",
        "variant_attributes",
        ["tenant_id", "variant_id"],
        unique=False,
    )
    op.create_index(
        "idx_variant_attributes_value",
        "variant_attributes",
        ["tenant_id", "value"],
        unique=False,
    )
    op.create_index(
        op.f("ix_variant_attributes_dimension_id"),
        "variant_attributes",
        ["dimension_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_variant_attributes_id"),
        "variant_attributes",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_variant_attributes_tenant_id"),
        "variant_attributes",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_variant_attributes_variant_id"),
        "variant_attributes",
        ["variant_id"],
        unique=False,
    )
    op.create_table(
        "variant_barcodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("variant_id", sa.Integer(), nullable=False),
        sa.Column("barcode_type_id", sa.Integer(), nullable=False),
        sa.Column("barcode_value", sa.String(length=100), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("external_system_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["barcode_type_id"],
            ["barcode_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["external_system_id"],
            ["external_systems.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "barcode_value",
            name="uq_variant_barcodes_tenant_value",
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "variant_id",
            "barcode_type_id",
            name="uq_variant_barcodes_tenant_variant_type",
        ),
    )
    op.create_index(
        "idx_variant_barcodes_primary",
        "variant_barcodes",
        ["tenant_id", "is_primary"],
        unique=False,
    )
    op.create_index(
        "idx_variant_barcodes_tenant_type",
        "variant_barcodes",
        ["tenant_id", "barcode_type_id"],
        unique=False,
    )
    op.create_index(
        "idx_variant_barcodes_tenant_variant",
        "variant_barcodes",
        ["tenant_id", "variant_id"],
        unique=False,
    )
    op.create_index(
        "idx_variant_barcodes_value",
        "variant_barcodes",
        ["tenant_id", "barcode_value"],
        unique=False,
    )
    op.create_index(
        op.f("ix_variant_barcodes_barcode_type_id"),
        "variant_barcodes",
        ["barcode_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_variant_barcodes_id"),
        "variant_barcodes",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_variant_barcodes_tenant_id"),
        "variant_barcodes",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_variant_barcodes_variant_id"),
        "variant_barcodes",
        ["variant_id"],
        unique=False,
    )
    op.alter_column(
        "products", "is_active", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "products", "is_available", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.drop_index("idx_products_handle", table_name="products")
    op.drop_index("idx_products_inventory", table_name="products")
    op.drop_index("idx_products_published", table_name="products")
    op.drop_index("idx_products_tenant_status", table_name="products")
    op.drop_index("idx_products_type", table_name="products")
    op.drop_index("idx_products_vendor", table_name="products")
    op.drop_constraint("uq_products_handle", "products", type_="unique")
    op.create_index(
        "idx_products_new_handle",
        "products",
        ["tenant_id", "handle"],
        unique=False,
    )
    op.create_index(
        "idx_products_new_tenant_status",
        "products",
        ["tenant_id", "status"],
        unique=False,
    )
    op.create_index(
        "idx_products_new_tenant_type",
        "products",
        ["tenant_id", "product_type"],
        unique=False,
    )
    op.create_index(
        "idx_products_new_tenant_vendor",
        "products",
        ["tenant_id", "vendor"],
        unique=False,
    )
    op.create_index(
        op.f("ix_products_tenant_id"), "products", ["tenant_id"], unique=False
    )
    op.create_unique_constraint(
        "uq_products_new_tenant_handle", "products", ["tenant_id", "handle"]
    )
    op.drop_column("products", "online_store_url")
    op.drop_column("products", "external_data")
    op.drop_column("products", "tracks_inventory")
    op.drop_column("products", "tags")
    op.drop_column("products", "has_out_of_stock_variants")
    op.drop_column("products", "total_inventory")
    op.drop_column("products", "last_synced_at")
    op.drop_column("products", "price")
    op.drop_column("products", "published_at")
    op.drop_column("products", "variants")
    op.drop_column("products", "has_only_default_variant")
    op.drop_column("products", "compare_at_price")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "compare_at_price",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "has_only_default_variant",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "variants",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "published_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "price",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "last_synced_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "total_inventory", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "has_out_of_stock_variants",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "tags",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "tracks_inventory",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "external_data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "online_store_url",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(
        "uq_products_new_tenant_handle", "products", type_="unique"
    )
    op.drop_index(op.f("ix_products_tenant_id"), table_name="products")
    op.drop_index("idx_products_new_tenant_vendor", table_name="products")
    op.drop_index("idx_products_new_tenant_type", table_name="products")
    op.drop_index("idx_products_new_tenant_status", table_name="products")
    op.drop_index("idx_products_new_handle", table_name="products")
    op.create_unique_constraint("uq_products_handle", "products", ["handle"])
    op.create_index(
        "idx_products_vendor", "products", ["vendor"], unique=False
    )
    op.create_index(
        "idx_products_type", "products", ["product_type"], unique=False
    )
    op.create_index(
        "idx_products_tenant_status",
        "products",
        ["tenant_id", "status"],
        unique=False,
    )
    op.create_index(
        "idx_products_published", "products", ["published_at"], unique=False
    )
    op.create_index(
        "idx_products_inventory", "products", ["total_inventory"], unique=False
    )
    op.create_index(
        "idx_products_handle", "products", ["handle"], unique=False
    )
    op.alter_column(
        "products", "is_available", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "products", "is_active", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.drop_index(
        op.f("ix_variant_barcodes_variant_id"), table_name="variant_barcodes"
    )
    op.drop_index(
        op.f("ix_variant_barcodes_tenant_id"), table_name="variant_barcodes"
    )
    op.drop_index(
        op.f("ix_variant_barcodes_id"), table_name="variant_barcodes"
    )
    op.drop_index(
        op.f("ix_variant_barcodes_barcode_type_id"),
        table_name="variant_barcodes",
    )
    op.drop_index("idx_variant_barcodes_value", table_name="variant_barcodes")
    op.drop_index(
        "idx_variant_barcodes_tenant_variant", table_name="variant_barcodes"
    )
    op.drop_index(
        "idx_variant_barcodes_tenant_type", table_name="variant_barcodes"
    )
    op.drop_index(
        "idx_variant_barcodes_primary", table_name="variant_barcodes"
    )
    op.drop_table("variant_barcodes")
    op.drop_index(
        op.f("ix_variant_attributes_variant_id"),
        table_name="variant_attributes",
    )
    op.drop_index(
        op.f("ix_variant_attributes_tenant_id"),
        table_name="variant_attributes",
    )
    op.drop_index(
        op.f("ix_variant_attributes_id"), table_name="variant_attributes"
    )
    op.drop_index(
        op.f("ix_variant_attributes_dimension_id"),
        table_name="variant_attributes",
    )
    op.drop_index(
        "idx_variant_attributes_value", table_name="variant_attributes"
    )
    op.drop_index(
        "idx_variant_attributes_tenant_variant",
        table_name="variant_attributes",
    )
    op.drop_index(
        "idx_variant_attributes_tenant_dimension",
        table_name="variant_attributes",
    )
    op.drop_table("variant_attributes")
    op.drop_index(
        op.f("ix_product_mappings_tenant_id"), table_name="product_mappings"
    )
    op.drop_index(
        op.f("ix_product_mappings_id"), table_name="product_mappings"
    )
    op.drop_index(
        op.f("ix_product_mappings_external_variant_id"),
        table_name="product_mappings",
    )
    op.drop_index(
        op.f("ix_product_mappings_external_system_id"),
        table_name="product_mappings",
    )
    op.drop_index(
        op.f("ix_product_mappings_external_product_id"),
        table_name="product_mappings",
    )
    op.drop_index(
        op.f("ix_product_mappings_core_variant_id"),
        table_name="product_mappings",
    )
    op.drop_index(
        op.f("ix_product_mappings_core_product_id"),
        table_name="product_mappings",
    )
    op.drop_index(
        "idx_product_mappings_tenant_sync", table_name="product_mappings"
    )
    op.drop_index(
        "idx_product_mappings_tenant_external", table_name="product_mappings"
    )
    op.drop_index(
        "idx_product_mappings_tenant_core", table_name="product_mappings"
    )
    op.drop_index(
        "idx_product_mappings_external_product", table_name="product_mappings"
    )
    op.drop_table("product_mappings")
    op.drop_index(
        op.f("ix_product_combination_items_tenant_id"),
        table_name="product_combination_items",
    )
    op.drop_index(
        op.f("ix_product_combination_items_item_variant_id"),
        table_name="product_combination_items",
    )
    op.drop_index(
        op.f("ix_product_combination_items_item_product_id"),
        table_name="product_combination_items",
    )
    op.drop_index(
        op.f("ix_product_combination_items_id"),
        table_name="product_combination_items",
    )
    op.drop_index(
        op.f("ix_product_combination_items_combination_id"),
        table_name="product_combination_items",
    )
    op.drop_index(
        "idx_product_combination_items_tenant_variant",
        table_name="product_combination_items",
    )
    op.drop_index(
        "idx_product_combination_items_tenant_product",
        table_name="product_combination_items",
    )
    op.drop_index(
        "idx_product_combination_items_tenant_combination",
        table_name="product_combination_items",
    )
    op.drop_table("product_combination_items")
    op.drop_index(
        op.f("ix_product_variants_tenant_id"), table_name="product_variants"
    )
    op.drop_index(
        op.f("ix_product_variants_sku"), table_name="product_variants"
    )
    op.drop_index(
        op.f("ix_product_variants_product_id"), table_name="product_variants"
    )
    op.drop_index(
        op.f("ix_product_variants_id"), table_name="product_variants"
    )
    op.drop_index(
        op.f("ix_product_variants_barcode"), table_name="product_variants"
    )
    op.drop_index(
        "idx_product_variants_tenant_sku", table_name="product_variants"
    )
    op.drop_index(
        "idx_product_variants_tenant_product", table_name="product_variants"
    )
    op.drop_index(
        "idx_product_variants_tenant_barcode", table_name="product_variants"
    )
    op.drop_index(
        "idx_product_variants_inventory", table_name="product_variants"
    )
    op.drop_table("product_variants")
    op.drop_index(op.f("ix_product_tags_tenant_id"), table_name="product_tags")
    op.drop_index(op.f("ix_product_tags_tag_id"), table_name="product_tags")
    op.drop_index(
        op.f("ix_product_tags_product_id"), table_name="product_tags"
    )
    op.drop_index(op.f("ix_product_tags_id"), table_name="product_tags")
    op.drop_index("idx_product_tags_tenant_tag", table_name="product_tags")
    op.drop_index("idx_product_tags_tenant_product", table_name="product_tags")
    op.drop_index("idx_product_tags_primary", table_name="product_tags")
    op.drop_table("product_tags")
    op.drop_index(
        op.f("ix_product_dimensions_tenant_id"),
        table_name="product_dimensions",
    )
    op.drop_index(
        op.f("ix_product_dimensions_product_id"),
        table_name="product_dimensions",
    )
    op.drop_index(
        op.f("ix_product_dimensions_id"), table_name="product_dimensions"
    )
    op.drop_index(
        "idx_product_dimensions_tenant_product",
        table_name="product_dimensions",
    )
    op.drop_index(
        "idx_product_dimensions_name", table_name="product_dimensions"
    )
    op.drop_table("product_dimensions")
    op.drop_index(
        op.f("ix_product_combinations_tenant_id"),
        table_name="product_combinations",
    )
    op.drop_index(
        op.f("ix_product_combinations_product_id"),
        table_name="product_combinations",
    )
    op.drop_index(
        op.f("ix_product_combinations_id"), table_name="product_combinations"
    )
    op.drop_index(
        "idx_product_combinations_tenant_type",
        table_name="product_combinations",
    )
    op.drop_index(
        "idx_product_combinations_tenant_product",
        table_name="product_combinations",
    )
    op.drop_table("product_combinations")
    op.drop_index(
        op.f("ix_external_products_tenant_id"), table_name="external_products"
    )
    op.drop_index(
        op.f("ix_external_products_id"), table_name="external_products"
    )
    op.drop_index(
        op.f("ix_external_products_external_variant_id"),
        table_name="external_products",
    )
    op.drop_index(
        op.f("ix_external_products_external_system_id"),
        table_name="external_products",
    )
    op.drop_index(
        op.f("ix_external_products_external_product_id"),
        table_name="external_products",
    )
    op.drop_index(
        "idx_external_products_tenant_variant", table_name="external_products"
    )
    op.drop_index(
        "idx_external_products_tenant_system", table_name="external_products"
    )
    op.drop_index(
        "idx_external_products_tenant_sync", table_name="external_products"
    )
    op.drop_index(
        "idx_external_products_tenant_status", table_name="external_products"
    )
    op.drop_index(
        "idx_external_products_tenant_product", table_name="external_products"
    )
    op.drop_table("external_products")
    op.drop_index(
        op.f("ix_barcode_types_tenant_id"), table_name="barcode_types"
    )
    op.drop_index(op.f("ix_barcode_types_id"), table_name="barcode_types")
    op.drop_index(
        "idx_barcode_types_tenant_system", table_name="barcode_types"
    )
    op.drop_index("idx_barcode_types_tenant_name", table_name="barcode_types")
    op.drop_table("barcode_types")
    op.drop_index(op.f("ix_tags_tenant_id"), table_name="tags")
    op.drop_index(op.f("ix_tags_id"), table_name="tags")
    op.drop_index("idx_tags_tenant_name", table_name="tags")
    op.drop_index("idx_tags_tenant_category", table_name="tags")
    op.drop_table("tags")
    # ### end Alembic commands ###
