"""Add sync config and job models

Revision ID: cbc267b6575b
Revises: 98f3e8fc9895
Create Date: 2025-08-13 22:22:17.744228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cbc267b6575b"
down_revision = "98f3e8fc9895"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
