"""Add last_product_sync_at to external_systems

Revision ID: 98f3e8fc9895
Revises: 07810f82b1ea
Create Date: 2025-08-13 22:02:03.722172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "98f3e8fc9895"
down_revision = "07810f82b1ea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "external_systems",
        sa.Column(
            "last_product_sync_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("external_systems", "last_product_sync_at")
    # ### end Alembic commands ###
