"""Add external_order_id and external_order_number to SCMOrder

Revision ID: 47a150b7658f
Revises: a0714620406e
Create Date: 2025-09-23 06:30:54.003521

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "47a150b7658f"
down_revision = "a0714620406e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 检查并删除约束（如果存在）
    connection = op.get_bind()
    inspector = sa.inspect(connection)

    # 检查约束是否存在
    constraints = inspector.get_unique_constraints("products")
    constraint_names = [constraint["name"] for constraint in constraints]

    if "uq_products_handle" in constraint_names:
        op.drop_constraint("uq_products_handle", "products", type_="unique")

    op.add_column(
        "scm_orders",
        sa.Column("external_order_id", sa.String(), nullable=True),
    )
    op.add_column(
        "scm_orders",
        sa.Column("external_order_number", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scm_orders", "external_order_number")
    op.drop_column("scm_orders", "external_order_id")

    # 检查并创建约束（如果不存在）
    connection = op.get_bind()
    inspector = sa.inspect(connection)

    # 检查约束是否存在
    constraints = inspector.get_unique_constraints("products")
    constraint_names = [constraint["name"] for constraint in constraints]

    if "uq_products_handle" not in constraint_names:
        op.create_unique_constraint("uq_products_handle", "products", ["handle"])
    # ### end Alembic commands ###
