"""remove_user_keys_table

Revision ID: 96172cd884f4
Revises: 3788d990929b
Create Date: 2025-08-25 01:04:19.973294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "96172cd884f4"
down_revision = "3788d990929b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop user_keys table as it's not being used
    # All authentication now uses tenant-level keys from tenants table
    op.drop_table("user_keys")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate user_keys table
    op.create_table(
        "user_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("key_id", sa.String(), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("key_type", sa.String(), nullable=False),
        sa.Column("key_size", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ),
        sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_user_keys_id"), "user_keys", ["id"], unique=False)
    op.create_index(op.f("ix_user_keys_key_id"), "user_keys", ["key_id"], unique=True)
    # ### end Alembic commands ###
