"""Add external_order_id and external_order_number to SCMOrder

Revision ID: 47a150b7658f
Revises: a0714620406e
Create Date: 2025-09-23 06:30:54.003521

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "47a150b7658f"
down_revision = "a0714620406e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_products_handle", "products", type_="unique")
    op.add_column(
        "scm_orders",
        sa.Column("external_order_id", sa.String(), nullable=True),
    )
    op.add_column(
        "scm_orders",
        sa.Column("external_order_number", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scm_orders", "external_order_number")
    op.drop_column("scm_orders", "external_order_id")
    op.create_unique_constraint("uq_products_handle", "products", ["handle"])
    # ### end Alembic commands ###
