"""add last_product_sync_at to external_systems

Revision ID: 20250814_1315
Revises: 49ebd303fd21
Create Date: 2025-08-14 13:15:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "20250814_1315"
down_revision = "49ebd303fd21"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_systems', sa.Column('last_product_sync_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_systems', 'last_product_sync_at')
    # ### end Alembic commands ###
